export const TRACK_HIGHLIGHT_BOOST = 0.4;
export const TRACK_EPSILON = 1e-3;
export const TRACK_HIT_TEST_MIN_DISTANCE = 6;
export const DEFAULT_TRACK_LINE_WIDTH = 1;
export const FOLLOWED_TRACK_LINE_WIDTH_MULTIPLIER = 1.35;
export const SELECTED_TRACK_LINE_WIDTH_MULTIPLIER = 1.5;
export const DEFAULT_TRACK_OPACITY = 0.9;
